services:
  mysql:
    container_name: 'user-sql-container'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=userdatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
